### ISSUE TITLE
Integrate extension with docker container 

### ISSUE THREAD

**Issue by DanielSSilva** [ironmansoftware/universal-code#8]
Not sure of the correct order, but if I'm not mistaken, I've created a docker container and then installed the PSU extension.
By default it did not populated the required fields on the settings. I've manually set the server path to point to http://localhost:5000 and restarted the VSCode. After that, I have some configurations set, but I don't think it has properly launched (image below).

Can you help me figure out if I'm doing anything wrong?
Thanks!

![image](https://user-images.githubusercontent.com/6862119/95917420-244fba80-0da2-11eb-809a-a8d9da05d39b.png)

**Comment by adamdriscoll** [comment]
Sorry for the delay in responding to this. We've redone how to extension works. It required some changes to Universal itself that so that we could modify the configuration files remotely.  You'll now be able to connect to docker containers appropriately and manage them. 

The Server Path setting is actually for the Universal.Server.exe executable. We've moved away from downloading the executable directly and now just rely on the user to enter the URL of their server. Automatically downloading and unzipping the PSU server was problematic and confusing to users. 

Now when you start the extension, it will just prompt for a URL and app token and then connect to your server.
